### ISSUE TITLE
Delete icon should be removed for "Unlabeled" label

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1178]
**Describe the bug**
Edit the "Unlabeled" label. The text is not enterable, like it should be. 

- [x] But the delete icon exists on toolbar, which should not. 

Clicking it brings up the message "Do you want to remove the bookmark label "__Unlabeled__"?"

- [x] Also, the text in the field shows "Unlabelled" (with double "L"). It should just be 1 letter "L"

**Bug was found on And Bible version**
Build 529

**Expected behavior**
The delete icon should be hidden in this "Unlabeled" label.

**Screenshots:**
![image](https://user-images.githubusercontent.com/35117769/123338818-b0f07200-d506-11eb-96b4-28a0d7c45051.png)

**Comment by agrogers** [comment]
Should we able to edit that label at all? But I can't find how you did
that. I have never seen the unlabeled label to edit it.

And it seems Unlabeled and Unlabelled with two Ls are both correct
spellings. We should be consistent in its use.

**Comment by timbze** [comment]
@agrogers 
The reason for editing is that you can set a different default color for it. But I guess also the "This workspace" section should be removed for it. Or perhaps now that we can set a default label to apply we should disabled editing it. I think editing was enabled because people are used to default yellow? highlights from before. That way that can be changed back.

Thinking about existing users who would have a lot of unlabeled bookmarks, it would be better to leave the color editable so they can change it back if they complain about their bookmark colors having changed.

The "Unlabel" for me comes after bookmarks that I start with a dot (.), and then a "Speak" bookmark, then the Unlabeled.

**Comment by tuomas2** [comment]
Fixed "Unlabelled"-> "Unlabeled" in Transifex (en_gb)

**Comment by tuomas2** [comment]
Color adjustment should be there, but most of other options not

**Comment by tuomas2** [comment]
Color and underline options.. not favourite etc.

**Comment by agrogers** [comment]
Yes, that makes sense.

But I am still not sure how to get to that setting...

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Main menu -> manage labels

**Comment by agrogers** [comment]
Ah, I see, I was looking for it under 'U'. Instead it is before 'A' and
after numbers

[image: image.png]

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
